[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200

board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.flash_mode = dio
board_build.partitions = partitions.csv

; OPI PSRAM
board_build.arduino.memory_type = qio_opi

[env:native]
platform = native
test_framework = unity
build_flags =
    -std=c++17
    -I include
    -lpthread
    -lutil
test_filter = test_native_*

[env:emulator]
platform = native
build_src_filter = -<src/> +<../emu/>
build_flags =
    -std=c++17
    -I include
    -I/usr/include/SDL2
    -D_REENTRANT
    -lSDL2
    -lssl
    -lcrypto
    -lpthread
    -lutil
