boot_upload_timeout: 180
ftp:
  password: WeY0JmzjCYsjvppK7iW9JVcmRAop7hww
  port: 21
  remote_path: /
  server: eu-central-1.sftpcloud.io
  username: 38ee2e9547134464a5482acb56a97a76
http_upload:
  chunk_size: 65536
  url_base: http://b03d97337e8cfa.lhr.life/upload
max_retries: 3
mount_point: /mnt/usb_logs
outbox_dir: /home/cedric/outbox
poll_interval: 30
quiet_window_seconds: 30
retry_delay: 10
upload_check_interval: 300
upload_method: ftp
virtual_disk_path: /dev/mmcblk0p3
wifi_ap:
  channel: 6
  ssid: AirBridge
